apiVersion: v2
name: vault
description: An umbrella Helm chart with a Vault instance which can be auto-activated
type: application
version: 0.0.29
dependencies:
  - name: vault
    version: "0.19.0"
    repository: "https://helm.releases.hashicorp.com"
  - name: vaultconfig
    version: "0.0.3"
    repository: "https://helm.chenchik.me/"
