apiVersion: v2
name: web-app
description: A Helm chart for adding arbitry web app to k8s
version: 0.1.3
dependencies:
  - name: vault-init
    version: "~0.0.1"
    condition: vault-activate.enabled
    repository: "https://chenchik.me/helm-charts"
