apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  namespace: "{{ .Values.vault.server.namespace }}"
data:
  check-vault-running.sh: |-
    #!/bin/ash
    for attempt in `seq 15`; do
      if [ "$attempt" -eq 15 ]; then
        echo "VAULT NOT REACHABLE"
        exit 1
      elif vault status; then
        echo "VAULT OK EXITING"
        exit 0
      elif [ "$?" = "2" ]; then
        echo "VAULT SEALED"
        exit 0
      else
        echo "sleeping for $attempt"
        sleep "$attempt"
      fi
    done
