image:
  repository: vault
# global:
#   vault:
#     server:
#       url: "http://vault.vault:8200"
#       namespace: vault
#       token:
#        secretName: secret-with-vault-token
#        secretKey: root_token
