{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
data: 
  {{- range $k, $v :=  .Values.config }}
  {{- if contains "\n" $v }}
  {{ $k }}: |- 
{{ $v | indent 4 }}
  {{- else }}
  {{ $k }}: '{{ $v }}'
  {{- end }}
  {{- end }}
{{- end }}