apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.name }}

spec:
  replicas: 1
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: {{ .Values.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.name }}

      {{- if .Values.vaultSecrets.toMount.enabled }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: {{ .Values.vaultSecrets.vaultRole | default .Values.name }}
        vault.hashicorp.com/agent-inject-secret-spawn: "{{ .Values.vaultSecrets.server.kvEndpoint }}/{{ .Values.vaultSecrets.secretPath }}"
        vault.hashicorp.com/secret-volume-path-spawn: "{{ .Values.vaultSecrets.toMount.mountPath }}"
        vault.hashicorp.com/agent-inject-template-spawn: |
          {{- `
          {{- with secret "`}}{{ .Values.vaultSecrets.server.kvEndpoint }}/data/{{ .Values.vaultSecrets.secretPath }}{{`" -}}
          {{- range $k, $v := .Data.data }}
          echo {{ $v }} > `}}{{ .Values.vaultSecrets.toMount.mountPath }}{{`/{{ $k }}
          {{- end }}{{ end }}
          rm `}}{{ .Values.vaultSecrets.toMount.mountPath }}{{`/spawn
          `}}
        vault.hashicorp.com/agent-inject-command-spawn: "cat {{ .Values.vaultSecrets.toMount.mountPath }}/spawn | sh --"
      {{- end }}
    spec:
      {{- if or .Values.vaultSecrets.toMount.enabled .Values.vaultSecrets.toEnv.enabled }}
      serviceAccountName: {{ .Values.name }}
      {{- end }}

      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}

      containers:
        - name: {{ .Values.name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          {{- if or .Values.config .Values.envSecrets .Values.vaultSecrets.toEnv.enabled }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{ .Values.name }}
            {{- end}}
            {{- if .Values.vaultSecrets.toEnv.enabled }}
            - secretRef:
                name: {{ .Values.name }}-vault-secret
            {{- end}}            
            {{- if .Values.envSecrets }}
            - secretRef:
                name: {{ .Values.envSecrets }}
            {{- end }}
          {{- end }}
      