---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
      namespace: "{{ .Release.Namespace }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
        namespace: "{{ .Release.Namespace }}"
      annotations:
        {{ include "vaultinject.Annotations" . | indent 8 }}
    spec:
      {{ include "vaultinject.serviceAccountName" . | indent 6 }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: "{{ .Release.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:  
            {{ include "vaultinject.envFrom" . | indent 12 }}
            {{- if .Values.config }}
            - configMapRef:
                name: "{{ .Release.Name }}"
            {{- end}}
            {{- if .Values.envSecrets }}
            - secretRef:
                name: {{ .Values.envSecrets }}
            {{- end }}
