{{- if .Values.ingressHost }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: {{ .Values.name }}

spec:
  entryPoints:
    - websecure

  routes:
    - kind: Rule
      match: Host(`{{.Values.ingressHost}}`)

      services:
        - name: {{ .Values.name }}
          port: {{ .Values.service.servicePort }}

  tls:
    certResolver: acme-http
{{- end }}