{{- if .Values.ingressHost }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"

spec:
  entryPoints:
    - {{ .Values.ingressEntryPoint | quote }}

  routes:
    - kind: Rule
      match: Host(`{{.Values.ingressHost}}`)

      services:
        - name: "{{ .Release.Name }}"
          port: {{ .Values.service.servicePort }}

  {{- if eq .Values.ingressEntryPoint "websecure" }}
  tls:
    certResolver: acme-http
  {{- end }}

{{- end }}