name: postgres

image:
  repository: postgres
  pullPolicy: IfNotPresent

vault:
  app:
    injectSecrets:
      toFiles: true
      toEnv: true

      keysToEnv:
        - POSTGRES_PASSWORD

      pathToSecret: "db"
      mountPath: /secrets
      policy: postgres-inject
