apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{.Values.name}}

spec:
  replicas: 1
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: {{.Values.name}}

  template:
    metadata:
      labels:
        app: {{.Values.name}}

      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: {{.Values.name}}
        vault.hashicorp.com/agent-inject-secret-spawn: "kv/data/api/{{.Values.environment}}"
        vault.hashicorp.com/agent-inject-template-spawn: |
          {{- `
          {{- with secret "kv/data/api/`}}{{.Values.environment}}{{`" -}}
          {{- range $k, $v := .Data.data }}
          echo {{ $v }} > /vault/secrets/{{ $k }}
          {{- end }}{{ end }}
          rm /vault/secrets/spawn
          `}}
        vault.hashicorp.com/agent-inject-command-spawn: "cat /vault/secrets/spawn | sh --"

    spec:
      serviceAccountName: {{.Values.name}}

      containers:
        - image: {{.Values.image}}
          name: {{.Values.name}}

          ports:
            - containerPort: {{.Values.targetPort}}

          env:
            - name: API_ENV_STATE
              value: {{.Values.environment}}
            - name: API_SECRETS_PATH
              value: "/vault/secrets"

      imagePullSecrets:
        - name: {{.Values.pullSecret}}
