apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: {{ .Values.name }}

spec:
  entryPoints:
    - websecure

  routes:
    - kind: Rule
      match: Host(`{{.Values.host}}`)

      services:
        - name: {{ .Values.name }}
          port: 80

  tls:
    certResolver: acme-http
