name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          "${GITHUB_WORKSPACE}/test.sh"

      - name: Helm Deps
        run: |
          for dir in $(ls -d charts/*); do
            helm dependency update $dir;
          done
          helm repo add self https://helm.chenchik.me
          helm repo add hashicorp https://helm.releases.hashicorp.com

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: ".cr-index"
          destination: "helm.chenchik.me"
          parent: false
          headers: |-
            cache-control: public, max-age=0
